In [1]:
import numpy as np
import torch

In [2]:
# Série temporelle
data = np.array([1,2,3,4,5,6,7,8,9,10], dtype=float)

window_size = 4          # sequence_length
input_size = 1

def sliding_window(sequence, window_size):
    X, y = [], []
    for i in range(len(sequence) - window_size):
        X.append(sequence[i:i+window_size])   # fenêtre
        y.append(sequence[i+window_size])     # cible
    return np.array(X), np.array(y)

X, y = sliding_window(data, window_size)

print("Avant PyTorch :")
print("X shape =", X.shape)   # (batch_size, sequence_length)
print("y shape =", y.shape)   # (batch_size,)
print("\t")
print("Voici les sequences de X:\n",X,"\n")
print("Voici les sequences de y: \n",y)


Avant PyTorch :
X shape = (6, 4)
y shape = (6,)
	
Voici les sequences de X:
 [[1. 2. 3. 4.]
 [2. 3. 4. 5.]
 [3. 4. 5. 6.]
 [4. 5. 6. 7.]
 [5. 6. 7. 8.]
 [6. 7. 8. 9.]] 

Voici les sequences de y: 
 [ 5.  6.  7.  8.  9. 10.]


batch_size = nombre de fenêtres

sequence_length = window_size

input_size = 1 (une seule variable par pas de temps)