In [1]:
import numpy as np

In [3]:
def sliding_window(sequence, window_size):
    X, y = [], []
    for i in range(len(sequence) - window_size):
        X.append(sequence[i:i + window_size])
        y.append(sequence[i + window_size])
    return np.array(X), np.array(y)

# Série temporelle
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

window_size = 3
X, y = sliding_window(data, window_size)

print("Entrées X :")
print(X)
print("Cibles y :")
print(y)

Entrées X :
[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]]
Cibles y :
[4 5 6 7 8 9]
